[package]
name = "concrete_ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete_ast = { version = "0.1.0", path = "../concrete_ast" }
generational-arena = "0.2.9"
tracing.workspace = true
